server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Если файл не найден, отдаем index.html (нужно для React Router)
        try_files $uri $uri/ /index.html;
    }

    # Оптимизация для кэширования статики (опционально, но полезно)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}