events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream react_app {
        server client:80;  
    }

    server {
        listen 80;
        server_name alexanderloskutov22.ru;

        location / {
            proxy_pass http://react_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Для SPA — если нужен fallback на index.html
        # location / {
        #     try_files $uri $uri/ /index.html;
        # }
    }
}